-- MySQL Script generated by MySQL Workbench
-- Sun Nov 21 19:37:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema casicruzroja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `casicruzroja` ;

-- -----------------------------------------------------
-- Schema casicruzroja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casicruzroja` DEFAULT CHARACTER SET utf8 ;
USE `casicruzroja` ;

-- -----------------------------------------------------
-- Table `casicruzroja`.`cod_postal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`cod_postal` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`cod_postal` (
  `cod_postal` INT NOT NULL,
  `poblacion` VARCHAR(100) NULL,
  `provinciaid` INT NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_postal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`voluntarix`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`voluntarix` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`voluntarix` (
  `dni_voluntarix` VARCHAR(9) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `apell1` VARCHAR(45) NULL,
  `apell2` VARCHAR(45) NULL,
  `telef_personal` VARCHAR(13) NULL,
  `telef_emergencias` VARCHAR(13) NULL,
  `idiomas` VARCHAR(90) NULL,
  `sede_idsede` INT NOT NULL,
  `tipo` TINYINT NULL,
  `sani_profesion` VARCHAR(45) NULL,
  `sani_disponibilidad` TINYINT NULL,
  PRIMARY KEY (`dni_voluntarix`, `sede_idsede`),
  INDEX `fk_voluntarix_sede1_idx` (`sede_idsede` ASC) VISIBLE,
  CONSTRAINT `fk_voluntarix_sede1`
    FOREIGN KEY (`sede_idsede`)
    REFERENCES `casicruzroja`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`sede` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`sede` (
  `idsede` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `cod_postal_cod_postal` INT NOT NULL,
  `director_a` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idsede`, `cod_postal_cod_postal`, `director_a`),
  INDEX `fk_sede_cod_postal1_idx` (`cod_postal_cod_postal` ASC) VISIBLE,
  INDEX `fk_sede_voluntarix1_idx` (`director_a` ASC) VISIBLE,
  CONSTRAINT `fk_sede_cod_postal1`
    FOREIGN KEY (`cod_postal_cod_postal`)
    REFERENCES `casicruzroja`.`cod_postal` (`cod_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sede_voluntarix1`
    FOREIGN KEY (`director_a`)
    REFERENCES `casicruzroja`.`voluntarix` (`dni_voluntarix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`colaborador` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`colaborador` (
  `nif` VARCHAR(15) NOT NULL,
  `poc_nombre` VARCHAR(150) NULL,
  `area_operaciones` VARCHAR(45) NULL,
  `poc_tel` VARCHAR(20) NULL,
  `poc_emaill` VARCHAR(150) NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`evento` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`evento` (
  `cod_evento` INT NOT NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `sede_idsede` INT NOT NULL,
  `colaborador_nif` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_evento`, `sede_idsede`, `colaborador_nif`),
  INDEX `fk_evento_sede1_idx` (`sede_idsede` ASC) VISIBLE,
  INDEX `fk_evento_colaborador1_idx` (`colaborador_nif` ASC) VISIBLE,
  CONSTRAINT `fk_evento_sede1`
    FOREIGN KEY (`sede_idsede`)
    REFERENCES `casicruzroja`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_colaborador1`
    FOREIGN KEY (`colaborador_nif`)
    REFERENCES `casicruzroja`.`colaborador` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`socix`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`socix` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`socix` (
  `dni_socio` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apell1` VARCHAR(45) NULL,
  `apell2` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  `correo_e` VARCHAR(45) NULL,
  `cod_postal_cod_postal` INT NULL,
  `sede_idsede` INT NULL,
  `evento_cod_evento` INT NULL,
  `cuota_tipo` VARCHAR(45) NULL,
  `cuota_importe` INT NULL,
  `cuota_CC` VARCHAR(45) NULL,
  PRIMARY KEY (`dni_socio`),
  INDEX `fk_socio_cod_postal1_idx` (`cod_postal_cod_postal` ASC) VISIBLE,
  INDEX `fk_socio_sede1_idx` (`sede_idsede` ASC) VISIBLE,
  INDEX `fk_socix_evento1_idx` (`evento_cod_evento` ASC) VISIBLE,
  CONSTRAINT `fk_socio_cod_postal1`
    FOREIGN KEY (`cod_postal_cod_postal`)
    REFERENCES `casicruzroja`.`cod_postal` (`cod_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_sede1`
    FOREIGN KEY (`sede_idsede`)
    REFERENCES `casicruzroja`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socix_evento1`
    FOREIGN KEY (`evento_cod_evento`)
    REFERENCES `casicruzroja`.`evento` (`cod_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`cuotas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`cuotas` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`cuotas` (
  `anio_mes` INT NOT NULL,
  `socio_dni_socio` VARCHAR(9) NOT NULL,
  `importe` INT NULL,
  PRIMARY KEY (`anio_mes`, `socio_dni_socio`),
  INDEX `fk_cuotas_socio_idx` (`socio_dni_socio` ASC) VISIBLE,
  CONSTRAINT `fk_cuotas_socio`
    FOREIGN KEY (`socio_dni_socio`)
    REFERENCES `casicruzroja`.`socix` (`dni_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`equipo` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`equipo` (
  `id_equipo` INT NOT NULL,
  `especialidad` VARCHAR(145) NULL,
  PRIMARY KEY (`id_equipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`voluntarix_has_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`voluntarix_has_equipo` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`voluntarix_has_equipo` (
  `voluntarix_dni_voluntarix` VARCHAR(9) NOT NULL,
  `equipo_id_equipo` INT NOT NULL,
  PRIMARY KEY (`voluntarix_dni_voluntarix`, `equipo_id_equipo`),
  INDEX `fk_voluntarix_has_equipo_equipo1_idx` (`equipo_id_equipo` ASC) VISIBLE,
  INDEX `fk_voluntarix_has_equipo_voluntarix1_idx` (`voluntarix_dni_voluntarix` ASC) VISIBLE,
  CONSTRAINT `fk_voluntarix_has_equipo_voluntarix1`
    FOREIGN KEY (`voluntarix_dni_voluntarix`)
    REFERENCES `casicruzroja`.`voluntarix` (`dni_voluntarix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntarix_has_equipo_equipo1`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `casicruzroja`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`envio` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`envio` (
  `idenvio` INT NOT NULL,
  `notas` VARCHAR(45) NULL,
  PRIMARY KEY (`idenvio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`mision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`mision` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`mision` (
  `idmision` INT NOT NULL,
  `destino` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `sede_idsede` INT NOT NULL,
  `equipo_id_equipo` INT NOT NULL,
  `envio_idenvio` INT NULL,
  PRIMARY KEY (`idmision`, `sede_idsede`, `equipo_id_equipo`),
  INDEX `fk_mision_sede1_idx` (`sede_idsede` ASC) VISIBLE,
  INDEX `fk_mision_equipo1_idx` (`equipo_id_equipo` ASC) VISIBLE,
  INDEX `fk_mision_envio1_idx` (`envio_idenvio` ASC) VISIBLE,
  CONSTRAINT `fk_mision_sede1`
    FOREIGN KEY (`sede_idsede`)
    REFERENCES `casicruzroja`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mision_equipo1`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `casicruzroja`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mision_envio1`
    FOREIGN KEY (`envio_idenvio`)
    REFERENCES `casicruzroja`.`envio` (`idenvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`material` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`material` (
  `idmaterial` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `colaborador_nif` VARCHAR(15) NULL,
  `cantidad_donada` VARCHAR(45) NULL,
  PRIMARY KEY (`idmaterial`),
  INDEX `fk_material_colaborador1_idx` (`colaborador_nif` ASC) VISIBLE,
  CONSTRAINT `fk_material_colaborador1`
    FOREIGN KEY (`colaborador_nif`)
    REFERENCES `casicruzroja`.`colaborador` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casicruzroja`.`envio_has_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casicruzroja`.`envio_has_material` ;

CREATE TABLE IF NOT EXISTS `casicruzroja`.`envio_has_material` (
  `envio_idenvio` INT NOT NULL,
  `material_idmaterial` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`envio_idenvio`, `material_idmaterial`),
  INDEX `fk_envio_has_material_material1_idx` (`material_idmaterial` ASC) VISIBLE,
  INDEX `fk_envio_has_material_envio1_idx` (`envio_idenvio` ASC) VISIBLE,
  CONSTRAINT `fk_envio_has_material_envio1`
    FOREIGN KEY (`envio_idenvio`)
    REFERENCES `casicruzroja`.`envio` (`idenvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_envio_has_material_material1`
    FOREIGN KEY (`material_idmaterial`)
    REFERENCES `casicruzroja`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
